name       : python-lhafile
version    : 0.2.2
release    : 6
source     :
    - https://files.pythonhosted.org/packages/30/ec/ab17b1f9b64a22f9aaf7d5f5f0474f8014ed18f7fab070776b417202df1d/lhafile-0.2.2.tar.gz : 794763b52c386465921734bf83234d87731ba9cdc8808433c9c7fbf33fed1b9f
license    : BSD-3-Clause
component  : programming.python
summary    : LHA archive support for Python
description: |
    LHA archive support for Python
builddeps  :
    - pkgconfig(python-2.7)
    - pkgconfig(python3)
    - python-setuptools
build      : |
    for py in "python" "python3"; do
        ${py} setup.py build
    done
install    : |
    for py in "python" "python3"; do
        ${py} setup.py install --root=%installroot% --no-compile -O0
    done
