name       : python-lhafile
version    : 0.2.2
release    : 7
source     :
    - https://files.pythonhosted.org/packages/30/ec/ab17b1f9b64a22f9aaf7d5f5f0474f8014ed18f7fab070776b417202df1d/lhafile-0.2.2.tar.gz : 794763b52c386465921734bf83234d87731ba9cdc8808433c9c7fbf33fed1b9f
license    : BSD-3-Clause
component  : programming.python
homepage   : https://fengestad.no/python-lhafile/
summary    : LHA archive support for Python
description: |
    LHA archive support for Python, primarily used as a component in FS-UAE Launcher to index and extract files from .lha archives.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
build      : |
    %python3_setup
install    : |
    %python3_install
